### ISSUE TITLE
unable to connect 

### ISSUE THREAD

**Issue by zerefati** [Ph3nol/NotificationPusher#140] opened 2017-02-17 22:47 UTC
RuntimeException in AbstractClient.php line 112:
Unable to connect: tls://gateway.sandbox.push.apple.com:2195: 2 (stream_socket_client(): unable to connect to tls://gateway.sandbox.push.apple.com:2195 (Connection refused))

Iam using Godaddy shared hosting ?

**Comment by seyfer** [comment] 2017-07-30 12:09
Looks like a problem with your infrastructure or with hosting environment.

**Comment by seyfer** [comment] 2017-07-30 12:11
Duplicate of https://github.com/Ph3nol/NotificationPusher/issues/133

**Comment by seyfer** [comment] 2017-07-30 12:14
@zerefati please check https://github.com/Ph3nol/NotificationPusher/issues/102 and https://github.com/Ph3nol/NotificationPusher/issues/133

**Closed by seyfer** 2017-07-30 12:14 UTC
Labels: bug, duplicate
